fix(ci.yaml) add missing lines at the end

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -148,4 +148,7 @@ jobs:
           echo "CI Pipeline Failed!"
           echo "========================================"
           echo ""
-          [ "${{ n
+          [ "${{ needs.build-and-unit-tests.result }}" == "failure" ] && echo "FAILED: Build or Unit Tests"
+          [ "${{ needs.mocked-integration-tests.result }}" == "failure" ] && echo "FAILED: Mocked Integration Tests"
+          echo ""
+          exit 1
